import os

# HUGGINGFACEHUB_API_TOKEN = os.getenv("HUGGINGFACEHUB_API_TOKEN")
TOKENIZER_NAME = os.getenv("TOKENIZER_NAME")
INFERENCE_SERVER_URL = os.getenv("INFERENCE_SERVER_URL")
OTLP_ENDPOINT = os.getenv("OTLP_ENDPOINT")
SVC_NAME = os.getenv("SVC_NAME")